### ISSUE TITLE
twitter widgets.js doesn't load due to use of plugins_url() when should be string

### ISSUE THREAD

**Issue by composerjk** [hyperaudio/wordpress-hyperaudio#127]
Already submitted fix in #123. Noting here since I see you're getting ready to submit (or maybe already have) to the WP plugins directory. Great.

See this line: https://github.com/hyperaudio/wordpress-hyperaudio/blob/a812c5411251de4a4ece6ce81330c71fb933725c/wp-hyperaudio/hyperaudio.php#L235

**Comment by maboa** [comment]
Merged. Many thanks! https://github.com/hyperaudio/wordpress-hyperaudio/pull/123

**Comment by maboa** [comment]
Ah. @composerjk Just noticed this doesn't actually work on external JS for me. It concatenates the URL to the base URL and produces a warning in the console:

`Loading failed for the <script> with source “http://example.com/wordpress/wp-content/plugins/wp-hyperaudio/https://platform.twitter.com/widgets.js?ver=1.0.0”.`

I'm going to remove it for now as I'm not sure why it's needed.
