### ISSUE TITLE
Feature request: add non-Soundcloud audio embed as possible media src

### ISSUE THREAD

**Issue by grantbarrett** [hyperaudio/wordpress-hyperaudio#94]
I'm pleased at the features offered by Hyperaudio but I am currently moving away from SoundCloud embeds toward WordPress audio block embeds that link MP3 audio files in a podcast feed. I'd love it if Hyperaudio would work with standard audio file formats, too. Thanks for considering this, if it's even possible.

**Comment by maboa** [comment]
Will definitely look into it.

**Comment by maboa** [comment]
You can also achieve compatibility with other native audio formats by using the `player` attribute. ie:

```
[hyperaudio src="http://example.com/drbob.ogg" player="nativeAudio"]<article><section><p><span data-m="1290" data-d="490">This, </span><span data-m="2100" data-d="270">co-</span><span data-m="2370" data-d="629">pilot </span><span data-m="3150" data-d="359">"Dr </span><span data-m="3510" data-d="410">Bob" </span><span data-m="4200" data-d="679">rocks!</span></p></section></article>[/hyperaudio]
```

**Comment by ataha24** [comment]
Following this issue...really happy with wp plugin and beyond excited to integrate it for a podcast! I was wondering about incorperating media from other sources (i.e., anchorfm or google podcasts)? Limited expertise in this domain, but I think these dont point to ".mp3" files directly? Alternatively, what are some recommended ways to link .mp3 files (relatively large files to host on wp domain) bypassing soundcloud upload (dont have the pro version for unlimited upload size)?
